prometheus:
  extraScrapeConfigs: |
    - job_name: 'web-api'
      scrape_interval: 2s
      metrics_path: /metrics
      static_configs:
        - targets:
          - "web-api.default:8000"
grafana:
  testFramework:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - "null"
    path: "/"
    pathType: Prefix
    ingressClassName: kong
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: "http://velocity-prometheus-server"
          access: proxy
          isDefault: true
